### ISSUE TITLE
it occurs a error after I train the model about thousands of iterations,do you know why

### ISSUE THREAD

**Issue by summerrr** [chanyn/HKRM#10]
[session 2][epoch  1][iter 3800] loss: 1.4599, lr: 5.00e-03
			fg/bg=(64/192), time cost: 116.947137
			rpn_cls: 0.2889, rpn_box: 0.2576, rcnn_cls: 0.8537, rcnn_box 0.3310, adja_loss 0.1700, adjr_loss 0.0107

it seems right,but it happens a error, I don't know the reason.

Traceback (most recent call last):
  File "trainval_HKRM.py", line 364, in <module>
    data = next(data_iter)
  File "/home/user10/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/home/user10/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/user10/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user10/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/user10/notebook/HKRM/lib/roi_data_layer/roibatchLoader.py", line 72, in __getitem__
    blobs = get_minibatch(minibatch_db, self._num_classes, self.random_scale_inds)
  File "/home/user10/notebook/HKRM/lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/home/user10/notebook/HKRM/lib/roi_data_layer/minibatch.py", line 75, in _get_image_blob
    im = im[:,:,::-1]
IndexError: too many indices for array

**Comment by chanyn** [comment]
Maybe some images are missing, so "im" is valid. Please check your dataset.
